### ISSUE TITLE
Templates must be part of the config file

### ISSUE THREAD

**Issue by souhail-5** [souhail-5/zeed#12]
I think it would be better to do something like this:

```yaml
channels:
  - added
  - changed
  - deprecated
  - fixed
  - removed
  - security
templates:
  default: "{{range .Entries}}• {{.Text}}\n{{end}}" # a custom *default* template that override the built-in one
  slack: |
    *What's new?*
    {{range .Entries -}}
    - {{.Text}}
    {{end}}
```

than having to put channels config in a separate file, plus one file for each template.
